### ISSUE TITLE
点击上传或者预览提示“当前开发者未绑定此 appid,请到 mp 后台操作后重试”？

### ISSUE THREAD

**Issue by KittenYang** [gavinkwoe/weapp-ide-crack#11]
<img width="381" alt="2016-09-22 10 38 28" src="https://cloud.githubusercontent.com/assets/5517281/18752740/e86158de-8115-11e6-8022-b80deb968abe.png">

点击上传或者预览自动跳到了公众平台主页。
是因为我账号本身还不具备小程序资格吗？

**Comment by gavinkwoe** [comment]
还没遇到这个问题，其他人看一下有没解决办法

**Comment by KittenYang** [comment]
我知道了，确实是只有内测资格的 appid 才可以。
