### ISSUE TITLE
更新windowStores.js 后40001错误

### ISSUE THREAD

**Issue by etoah** [gavinkwoe/weapp-ide-crack#17]

**Comment by etoah** [comment]
![image](https://cloud.githubusercontent.com/assets/7630567/18754483/6f337b58-811b-11e6-9afd-cc2fc23e9680.png)

**Comment by MoienBowen** [comment]
MacOS 平台，没有扫码登录过程，点击“添加项目”后同样 40001。

**Comment by Rannie** [comment]
同样的问题

**Comment by swlfigo** [comment]
同样的问题

**Comment by mansonchor** [comment]
一边破解 微信一边封，无解的，洗洗睡吧

**Comment by jaderYang** [comment]
我服。 全是4001

**Comment by gavinkwoe** [comment]
正在尝试解决

**Comment by qfish** [comment]
重装0.9版本，不要替换windowStores.js

**Comment by gavinkwoe** [comment]
请更新并重新安装覆盖一下

**Comment by frankjunqi** [comment]
重新安装的时候，记得用0.7先登录，然后在用0.9的打开就可以了，不要替换windowStores.js.
