### ISSUE TITLE
0.7版的下载连接错误，打开是0.9

### ISSUE THREAD

**Issue by jakechan2012** [gavinkwoe/weapp-ide-crack#23]
百度: https://pan.baidu.com/s/1pLTKIqJ  
readme中的连接打开是0.9的

**Comment by JiandanDream** [comment]
2个版本的链接是一样的

**Comment by wu-leaf** [comment]
是啊，同样的链接。
求再分享下

**Comment by jiangyuseu** [comment]
同求，链接错了

**Comment by jakechan2012** [comment]
加群里下载吧

**Comment by net205** [comment]
“扫码无法登录”文字下面有：
http://dldir1.qq.com/WechatWebDev/release/0.7.0/wechat_web_devtools_0.7.0_x64.exe 
http://dldir1.qq.com/WechatWebDev/release/0.7.0/wechat_web_devtools_0.7.0.dmg

**Comment by fakefish** [comment]
我提交了0.7的网盘
