### ISSUE TITLE
Uncaught Error: Cannot find module './Create/create.js'

### ISSUE THREAD

**Issue by samlaudev** [gavinkwoe/weapp-ide-crack#31]
打开微信web开发者工具v0.9.092100，chrome出现Uncaught Error: Cannot find module './Create/create.js'的错误！

**Comment by samlaudev** [comment]
<img width="648" alt="screen shot 2016-09-23 at 10 23 43 am" src="https://cloud.githubusercontent.com/assets/2336442/18772275/2078b25a-8178-11e6-8f7d-3c46bb42e532.png">

**Comment by samlaudev** [comment]
<img width="607" alt="screen shot 2016-09-23 at 10 23 55 am" src="https://cloud.githubusercontent.com/assets/2336442/18772300/501872de-8178-11e6-908c-30d9f28b2938.png">
同时开发工具出现空白

**Comment by samlaudev** [comment]
已经自己解决了！从console来看，提示信息是加载模块失败。将微信开发工具的项目导入atom，然后搜索相关字符串，将修改一下加载模块语句就行了

**Comment by xiangzhai** [comment]
Hi @samlaudev 

修改了 package.nw/app/dist/components/ContainController.js 的 `s=require("    ./create/create.js")`

又提示 Error: Cannot find module './main.js'

```
find . -name "main.js"
./node_modules/mksnapshot/lib/main.js
./app/dist/weapp/quick/pages/main/main.js
./app/dist/js/weapp/quick/pages/main/main.js
./modified_modules/weinre/web/doc/scripts/main.js
```

貌似同级目录下没有该文件？

Regards,
Leslie Zhai

**Comment by xiangzhai** [comment]
v0.7.x倒是能工作～

![screenshot1](https://pbs.twimg.com/media/CtAs-fnUkAE4LGS.jpg)

![screenshot2](https://pbs.twimg.com/media/CtAtAHcVIAAtQxw.jpg)

![screenshot3](https://pbs.twimg.com/media/CtAtCJOUIAAC-sz.jpg)

![screenshot4](https://pbs.twimg.com/media/CtAtC5DUMAEFV9z.jpg)

用weapp能干嘛？开发**_Yet Another WebWx**_？！

**Comment by samlaudev** [comment]
有个Main.js文件，而不是main.js，m是大写的

**Comment by xiangzhai** [comment]
> 有个Main.js文件，而不是main.js，m是大写的

多谢！typo问题太多了。。。app/dist/components/debugger/debugger.js的`../purview/purview.js`要大写`../Purview/purview.js`

勉强能跑了：

![screenshot1](https://pbs.twimg.com/media/CtA0xlLUEAASuou.jpg)

![screenshot2](https://pbs.twimg.com/media/CtA0yeaVYAAs8UJ.jpg)

**Comment by samlaudev** [comment]
哈哈，能跑就好，现在玩玩而已

**Comment by xiangzhai** [comment]
Linux下编译wxml问题 https://github.com/gavinkwoe/weapp-ide-crack/issues/39
