### ISSUE TITLE
mac如何替换文件啊？

### ISSUE THREAD

**Issue by honelyboy** [gavinkwoe/weapp-ide-crack#41]
Mac下打开显示包内容之后无法替换文件，原因是文件是只读模式。求大神之路。

**Comment by dadademao** [comment]
同求啊，一直readOnly，尝试了很多方法都不行

**Comment by dadademao** [comment]
解决了，不要从finder 输入路径进去，应该在application文件目录下找到应用程序打开包内容就可以修改了

**Comment by gavinkwoe** [comment]
右键选「显示包内容」

**Comment by honelyboy** [comment]
先要安装程序，并允许打开程序。让后右键选［显示包内容］才能修改文件。
