### ISSUE TITLE
开发工具更新了，好像被封了？

### ISSUE THREAD

**Issue by malaimoo** [gavinkwoe/weapp-ide-crack#56]
无法创建新的项目了。

**Comment by malaimoo** [comment]
系统错误 {"baseresponse":{"errcode":40013,"errmsg":"invalid appid"}}

**Comment by jackgreentemp** [comment]
我这边也遇到了同样的情况

**Comment by jackgreentemp** [comment]
哈哈，腾讯的工程师发现了拼写错误，原来文件夹是“stroes”， 现在改为“stores”了，把新文件夹里的"projectStores.js"替换一下就可以了
