### ISSUE TITLE
进行文件替换之后无法进入IDE

### ISSUE THREAD

**Issue by GuiJu** [gavinkwoe/weapp-ide-crack#67]
本来可以进入IDE界面，但是按说明进行文件的相应替换之后，进入程序只有一片空白

**Comment by BuptStEve** [comment]
把在 `createstep.js` 里的这个

``` js
c = (require("../../stores/webviewStores.js"), 
```

改成这个...

``` js
c = (require("../../stroes/webviewStores.js"), 
```

**Comment by xiuxiuing** [comment]
下载的0.9.0921版本打开后，提示更新到0.9.0923版本，更新之后，会在stroes同目录多一个stores目录，应该替换stores目录的projectStores.js文件。

**Comment by ncscherb** [comment]
随便输入appid提示不能进入

**Comment by aikenw** [comment]
@BuptStEve 谢谢！
