### ISSUE TITLE
Uncaught Error: Cannot find module '../../stores/webviewStores.js'

### ISSUE THREAD

**Issue by codingWang** [gavinkwoe/weapp-ide-crack#68]
覆盖0.7版本安装0.9的，是stores和stroes的关系吗，怎么解决？

**Comment by Zhongzhe** [comment]
是的。
把在 createstep.js 里的这个

c = (require("../../stores/webviewStores.js"), 
改成这个...

c = (require("../../stroes/webviewStores.js"),

**Comment by codingWang** [comment]
已解决，非常感谢
