### ISSUE TITLE
微信扫码登录失败？

### ISSUE THREAD

**Issue by sofond** [gavinkwoe/weapp-ide-crack#7]
微信扫码登录失败？手机微信已经提示成功

登录失败，错误信息：please bind your wechat account to the appid first

**Comment by renpengben** [comment]
我也是

**Comment by gurongkang** [comment]
我也是

**Comment by sofond** [comment]
重启N次，扫码N次都是登录不了。

**Comment by chenyue404** [comment]
同

**Comment by yangbai1991** [comment]
同问

**Comment by Joyotang** [comment]
同问

**Comment by xiruoruo** [comment]
me too

**Comment by gavinkwoe** [comment]
多试几次，刚刚我也是

**Comment by Deain** [comment]
看来都是一样

**Comment by yuler** [comment]
@gavinkwoe 多试几次是多少次啊。

**Comment by xiaoliwe** [comment]
试了很多次均失败，我估计微信已经封住了。

**Comment by scaleryvan** [comment]
十次均失败，估计已经修复了

**Comment by LucianLiu6** [comment]
同失败，应该是已经修复了....来晚了

**Comment by liuxingchen1989** [comment]
是啊，换了俩微信都登陆不上

**Comment by frankjunqi** [comment]
我也是，登陆不上

**Comment by whiteath** [comment]
同。。。please bind your wechat account to the appid first

**Comment by Josscii** [comment]
来晚了。。。

**Comment by frankjunqi** [comment]
晚了

**Comment by bakso** [comment]
please bind your wechat account to the a

**Comment by solobearchn** [comment]
确实来晚了

**Comment by GZShi** [comment]
修改`dist/components/lunch/lunch.js`里面关于登录的判断代码可以跳过`appid`绑定的检测，但是后面创建项目的时候直接又调回登录窗口了。不知道正确的登录状态是怎样的，不然可以试试伪造一个正确的登录应答。

**Comment by Guolei1130** [comment]
有网友先用0.7登陆，安装0.9，破解，成功了

**Comment by yuler** [comment]
@Guolei1130 我测试了，可以

**Comment by gongchao** [comment]
@yuler 旧版本哪里下载呢？

**Comment by yuler** [comment]
http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455784140&token=&lang=zh_CN

**Comment by gavinkwoe** [comment]
见README有解决方案
