### ISSUE TITLE
MAC版本不显示wxml panel

### ISSUE THREAD

**Issue by isnolan** [gavinkwoe/weapp-ide-crack#74]
MAC安装完毕后，存在两个问题：
1、“无法加载以下来源的扩展程序： . 清单文件缺失或不可读。”
![2016-10-08 6 23 31](https://cloud.githubusercontent.com/assets/1823025/19212472/69494036-8d84-11e6-947e-0aa3fc186323.png)
2、不显示wxml、storage 等panel
![2016-10-08 6 22 04](https://cloud.githubusercontent.com/assets/1823025/19212463/4075f94c-8d84-11e6-9f2e-712f3322dbf5.png)

谁晓得啥原因哈？

**Comment by justnolanzh** [comment]
因为已经安装"微信web开发者工具"线上版本，所以安装这个测试版本后进行了改名操作，所以才会出现这俩异常现象，发出来给大家参考一下哈。
