### ISSUE TITLE
开发工具没开源？！

### ISSUE THREAD

**Issue by xiangzhai** [gavinkwoe/weapp-ide-crack#8]
您好 gavinkwoe，

我是微信KDE前端 https://github.com/xiangzhai/qwx 开发者，不知道开发工具为何没开源？！我可以帮忙移植到Linux平台，移植案例 https://github.com/robopeak/laserkbd

Leslie Zhai - KDE开发者 https://git.reviewboard.kde.org/users/lesliezhai

**Comment by gavinkwoe** [comment]
这是官方工具，不开源

**Comment by xiangzhai** [comment]
今天到办公室wine安装了一下，是用nw.js开发的，那等于是开源了 ;-)

![run with nw.js](https://pbs.twimg.com/media/CtAkDZCVUAARviu.jpg)

同样遇到 https://github.com/gavinkwoe/weapp-ide-crack/issues/31

**Comment by xiangzhai** [comment]
Fixed by LibreWeappIDE https://github.com/xiangzhai/LibreWeappIDE
